//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DebSystemProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int Id { get; set; }
        public Nullable<decimal> Value { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> FriendIdIn { get; set; }
        public Nullable<int> FriendIdOut { get; set; }
    
        public virtual Friend Friend { get; set; }
        public virtual Friend Friend1 { get; set; }
    }
}
